/**
 * Shared TypeScript types for Banco de Ideas
 * Centralizes all type definitions to avoid duplication
 */

/**
 * Message in the chat interface
 */
export type Message = {
    id: number;
    role: 'user' | 'assistant';
    content: React.ReactNode | string;
    plainText?: string; // For context memory
};

/**
 * Idea generated by AI (bisociation)
 */
export type Idea = {
    id: string | number;
    title: string;
    summary: string;
};

/**
 * Saved idea from database
 */
export type SavedIdea = {
    id: string;
    text: string;
    createdAt: string;
    category: 'user' | 'bisociation';
    userId?: string | null;
};

/**
 * API action types
 */
export type ApiAction = 'save' | 'similar' | 'analysis' | 'chat';

/**
 * API request payload
 */
export type AnalyzeRequest = {
    action: ApiAction;
    idea?: string;
    history?: Message[];
};

/**
 * API response payload
 */
export type AnalyzeResponse = {
    result?: string | Idea[];
    error?: string;
    message?: string;
};
